FROM python:3.10

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar requirements e instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del servicio
COPY . .

# Exponer puerto
EXPOSE 8002

# Comando para ejecutar el microservicio
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8002"]
